spring:
  application:
    name: jdbcgraphql

  threads:
    virtual:
      enabled: true

  
  # Enabling graphql playground
  graphql:
    graphiql:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true

server:
  port: 9191
